#!/bin/sh
set -e

if [ $# -gt 0 ]; then
    file=$1
else
    file=tv-spain.json
fi

status_ok=":green_heart:"
status_dead=":red_circle:"

echo "# TV-Online-TDT-Spain
Lista de URLs de canales TDT de España - Abrir directamente con VLC u otro reproductor de vídeo.

Manual: [Cómo abrir estos canales de TDT en VLC](https://www.softzone.es/2016/12/18/ver-la-tdt-online-streaming-utilizando-tan-solo-vlc/)

Plugin Kodi: Comprime la carpeta plugin.video.tdtiberia en un fichero zip con ese mismo nombre. Sigue la guia [instalar plugin en zip](http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files) para instalar el plugin.

## Status Update: **$(date +"%d-%m-%y")**

Status| Description
--- | --- |
$status_ok|OK
$status_dead|Link no accesible


Status | Canal | URL 
--- | --- | ---" 


while read i; do

#     echo $i
    # do stuff with $i
    #url=$(echo $i | jq -r '.link_m3u8')
    name=$(echo $i | jq -r '.name')
    id=$(echo $i | jq -r '.id')
    
    #Iterate each link of stream
    counter=0
    url= #reset
    stream_active="$status_dead" #Default disabled. Try to find one valid
    while read j; do
        [ ! -z $url ] && url="$url<br/>"
        url=$url$(echo $j | jq -r '.url')
        
        set +e
        request="$(curl --compressed -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" -m 10 --retry 2 --retry-delay 15 -s -v "$url" 2>&1)"
        set -e
        
        if [ "$(echo "$request"| grep -i "Content-Type:" | cut -d: -f2 | awk '{print $1}' | tr -dc '[[:print:]]')" == "application/vnd.apple.mpegurl" ] || echo "$request" | grep -qi "EXT-X-STREAM"; then
            stream_active="$status_ok" #If one stre
            jq "map((select(.id == $id) | .link[$counter].enabled) |= true)" $file | sponge $file
            #         echo "$request" > .log_ok_$id
        else
            jq "map((select(.id == $id) | .link[$counter].enabled) |= false)" $file | sponge $file
            #         echo "$request" > .log_$id
        fi
        
        let counter=$counter+1
    done <<<$(echo $i | jq -c '.link[]' )
    
    echo "$stream_active|$name|$url"

done <<<$(jq -c '.[]' $file)
